#!/usr/bin/env python3
"""Generate a synthetic HDL stress design of N gates.

Usage:
    tools/stress-gen.py --gates N [--out path.hdl]

Emits a long chain of NOT gates (`not g0 → w0 → not g1 → w1 → … → q`),
which is the simplest topology that gives the compiler a controlled
gate count for benchmarking. For more interesting designs, generate a
ripple-adder structure or copy-paste the chain output and wrap with
additional logic by hand.

Used by:
    - crates/rb-synthesis/benches/pathfinder_10k.rs (inline body)
    - crates/rb-synthesis/benches/sa_place_10k.rs (inline body)
    - examples/stress_10k.hdl (committed snapshot)
    - tests/end_to_end_us3.rs ripple-adder e2e

Per FR-V11 / SC-V03: the v2 compiler should handle ≥10 000 gates in
under 5 minutes on a typical developer laptop.
"""

import argparse
import sys


def emit_chain(n: int) -> str:
    if n < 1:
        raise ValueError("--gates must be >= 1")
    lines: list[str] = []
    lines.append("// Auto-generated by tools/stress-gen.py — do not hand-edit.")
    lines.append(f"// {n}-gate NOT chain for compiler stress testing.")
    lines.append("module chain(input a, output q);")
    # All wires declared up-front (the v1 grammar requires this).
    wires = ", ".join(f"w{i}" for i in range(n))
    lines.append(f"    wire {wires};")
    for i in range(n):
        src = "a" if i == 0 else f"w{i - 1}"
        lines.append(f"    not g{i}(.A({src}), .Y(w{i}));")
    lines.append(f"    not gq(.A(w{n - 1}), .Y(q));")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gates", type=int, required=True, help="number of NOT gates to emit")
    parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="output path (stdout if omitted)",
    )
    args = parser.parse_args()

    src = emit_chain(args.gates)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(src)
    else:
        sys.stdout.write(src)
    return 0


if __name__ == "__main__":
    sys.exit(main())
